main: us.ajg0702.queue.spigot.SpigotMain
version: "@VERSION@"
api-version: 1.13
author: ajgeiss0702
name: ajQueue
softdepend: [PlaceholderAPI]
commands:
   queue:
      aliases: [server, move, joinq, joinqueue]
      description: Queue for a server
   leavequeue:
      aliases: [leaveq]
      description: Leaves a queue